version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - sonarqube
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=admin
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    ports:
      - "5432:5432"
