pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: "1"))
    }
 
    environment {
        registryCredential = 'ecr:ap-southeast-1:awscreds'
        appRegistry = '178108053885.dkr.ecr.ap-southeast-1.amazonaws.com/appimg'
        vprofileRegistry = "https://178108053885.dkr.ecr.ap-southeast-1.amazonaws.com"
        cluster = "vproprod"
        service = "vproprodsvc"
    }

    stages {
        stage ('Deploy to Prod ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'ap-southeast-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }        
}